### ISSUE TITLE
NuGet unable to resolve AdaptiveTriggerLibrary (>= 1.1.1)

### ISSUE THREAD

**Issue by phaagar** [Herdo/AdaptiveTriggerLibrary#1]
Unfortunately, adding the AdaptiveTriggerLibrary v1.1 to my project via NuGet fails:

---

> Using source https://api.nuget.org/v3/index.json.
> Using source https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/.
> Restoring packages for UAP,Version=v10.0...
>  CACHE https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='AdaptiveTriggerLibrary'
>  CACHE https://az320820.vo.msecnd.net/v3-flatcontainer/adaptivetriggerlibrary/index.json
> Resolving conflicts for UAP,Version=v10.0...
> Unable to resolve AdaptiveTriggerLibrary (≥ 1.1.1) for UAP,Version=v10.0.

---

Adding any 1.0 version of AdaptiveTriggerLibrary still works though.

In any case: AdaptiveTriggerLibrary is a splendid thing!

**Comment by Herdo** [comment]
Hey @phaagar . I noticed it myself. Currently I'm not sure what's going on, due to I just increased the version numbers. I'm going to talk to the NuGet support.

**Comment by Herdo** [comment]
@phaagar NuGet is currently encounting server issues. There's no error in the package itself.  
You can still add the package by adding https://www.nuget.org/api/v2/ as a NuGet package source (as temporary workaround recommended by NuGet support).
Or you can download the package manually, and install it from a local package source.

**Comment by phaagar** [comment]
Thanks for the update. I will use one of the alternate installation routes then.

Sent from my Windows Phone
