### ISSUE TITLE
ConnectivityTrigger error on UWP

### ISSUE THREAD

**Issue by RaminMT** [Herdo/AdaptiveTriggerLibrary#6]
Hi, I'm using your nice library on my project.
I had trouble in using ConnectivityTrigger on project, when a changes made on network state I was getting the following error:
```the application called an interface that was marshalled for a different thread. (exception from hresult: 0x8001010e (rpc_e_wrong_thread))```

I've searched & said that the code should run on UI thread. After a lot of problem and tests, I found that the `SetActive(IsActive);` on line 68 of AdaptiveTriggerBase.cs is the cause of that error, I surrounded the block with a Dispatcher.RunAsync and errors gone.

**Comment by Herdo** [comment]
Thanks for the error report, @RaminMT - could you provide a small UWP app example showing the issue?

**Comment by RaminMT** [comment]
Hi,
Excuses for latency, My VS installation had been corrupted during latest update!!
Check out the sample for error: [ConnectivityTriggerSample.zip](https://github.com/Herdo/AdaptiveTriggerLibrary/files/1236110/ConnectivityTriggerSample.zip)

**Comment by Herdo** [comment]
@RaminMT Version 1.2.2 should fix the problem.

**Comment by RaminMT** [comment]
Thanks,
When it'll be available on nugget?

**Comment by Herdo** [comment]
@RaminMT It's already published.

**Comment by RaminMT** [comment]
Works great
Thanks man ;)
